// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240319184137_panth")]
    partial class panth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Divine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Divineid")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("pantheonId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Divineid");

                    b.HasIndex("pantheonId");

                    b.ToTable("Divines");
                });

            modelBuilder.Entity("API.Models.Pantheon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Pantheons");
                });

            modelBuilder.Entity("API.Models.Divine", b =>
                {
                    b.HasOne("API.Models.Divine", null)
                        .WithMany("aliases")
                        .HasForeignKey("Divineid");

                    b.HasOne("API.Models.Pantheon", "pantheon")
                        .WithMany("Divines")
                        .HasForeignKey("pantheonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pantheon");
                });

            modelBuilder.Entity("API.Models.Divine", b =>
                {
                    b.Navigation("aliases");
                });

            modelBuilder.Entity("API.Models.Pantheon", b =>
                {
                    b.Navigation("Divines");
                });
#pragma warning restore 612, 618
        }
    }
}
